FROM resin/rpi-raspbian
RUN apt-get update && apt-get install -y git python3 python3-pip && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ADD requirements.txt /tmp
ADD docker-compose-configs/eva.conf /root/eva/eva.conf
ADD docker-compose-configs/configs /root/eva/configs
RUN pip3 install --user -r /tmp/requirements.txt
WORKDIR /eva
CMD ["python3", "/eva/serve.py"]
